#!/usr/bin/env bash
# Inject complete onboarding sequence for /de:start routing.
# Only outputs when .design-engineer.yaml does NOT exist (new-to-plugin case).
# In configured projects, stays silent (exits with no output).

CONFIG=".design-engineer.yaml"

if [ ! -f "$CONFIG" ]; then
  cat <<'HOOK_EOF'
{"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext":"DESIGN_ENGINEER_PROJECT_STATE: new_to_plugin\n\nONBOARDING SEQUENCE — follow these steps when /de:start runs. Do not skip any step.\n\nSTEP 1: Ask ONE question (no text before it):\n  question=\"Welcome to Design Engineer Plugin. What brings you here?\"\n  header=\"Project type\"\n  options=[{label: \"New product idea\", description: \"Starting from scratch – I have an idea or a problem I want to solve\"}, {label: \"Existing project\", description: \"I already have a product, codebase, or designs – I want to improve, review, or add features\"}]\n\nAfter receiving the answer, follow the matching path:\n\nPATH A — \"New product idea\":\n  Load the meta-setup skill and proceed to its Step 2 (Detect Environment). The meta-setup skill handles the full new-product setup.\n\nPATH B — \"Existing project\":\n  Continue with steps 2–5 below. Do not skip any.\n\n  STEP 2: Ask goal question:\n    question=\"What would you like to do with your existing project?\"\n    header=\"Goal\"\n    options=[{label: \"Review what I have\", description: \"Audit quality, find UX issues, check accessibility\"}, {label: \"Implement from Figma\", description: \"I have designs ready to turn into code\"}, {label: \"Design a new feature\", description: \"Start the design thinking process for something new\"}, {label: \"Set up the dev workflow\", description: \"Configure AI-assisted development for this project\"}]\n\n  STEP 3: Ask mode question:\n    question=\"How do you want to work?\"\n    header=\"Mode\"\n    options=[{label: \"Guided mode (Recommended)\", description: \"Step by step – I share my thinking, ask questions, and you review each step\"}, {label: \"God mode\", description: \"Mostly automated – I plan and execute with minimal interruption. Faster but less control.\"}]\n\n  STEP 4: Run setup silently, then ask status line:\n    a) Run detect-environment.sh from the meta-setup skill scripts directory\n    b) Create .design-engineer.yaml with project type, selected mode, and detected environment\n    c) Scaffold docs/design/ folder via init-project-structure.sh from meta-setup scripts\n    d) Show brief environment results in plain language (checkmarks, no technical names)\n    e) Ask status line question:\n       question=\"Would you like to install the status line?\"\n       header=\"Status line\"\n       options=[{label: \"Yes (Recommended)\", description: \"Shows model, usage limits, context bar, and pipeline progress below every prompt\"}, {label: \"No\", description: \"Skip – re-run /de:start later to install\"}]\n    f) If Yes, install status line per meta-setup skill Step 5 instructions\n\n  STEP 5: Say \"You're all set. Let's get started.\" then load the /de: command matching the goal:\n    Review what I have -> /de:review\n    Implement from Figma -> /de:dev\n    Design a new feature -> /de:design\n    Set up the dev workflow -> /de:dev"}}
HOOK_EOF
fi
