#!/usr/bin/env bash
# Inject complete onboarding sequence for /de:start routing.
# Only outputs when .design-engineer.yaml does NOT exist (new-to-plugin case).
# In configured projects, stays silent (exits with no output).

CONFIG=".design-engineer.yaml"

if [ ! -f "$CONFIG" ]; then
  cat <<'HOOK_EOF'
{"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext":"DESIGN_ENGINEER_PROJECT_STATE: new_to_plugin\n\nONBOARDING SEQUENCE — complete all 4 steps in order when /de:start runs. Do not skip any step. Do not load any /de: command until step 4.\n\nSTEP 1: Make ONE AskUserQuestion call with these 2 questions (no text before it):\n  Q1: question=\"Welcome to Design Engineer Plugin. What brings you here?\" header=\"Project type\" options=[{label: \"New product idea\", description: \"Starting from scratch – I have an idea or a problem I want to solve\"}, {label: \"Existing project\", description: \"I already have a product, codebase, or designs – I want to improve, review, or add features\"}]\n  Q2: question=\"What would you like to do?\" header=\"Goal\" options=[{label: \"Review what I have\", description: \"Audit quality, find UX issues, check accessibility\"}, {label: \"Implement from Figma\", description: \"I have designs ready to turn into code\"}, {label: \"Design a new feature\", description: \"Start the design thinking process for something new\"}, {label: \"Set up the dev workflow\", description: \"Configure AI-assisted development for this project\"}]\n\nSTEP 2: After receiving step 1 answers, make another AskUserQuestion:\n  Q1: question=\"How do you want to work?\" header=\"Mode\" options=[{label: \"Guided mode (Recommended)\", description: \"Step by step – I share my thinking, ask questions, and you review each step\"}, {label: \"God mode\", description: \"Mostly automated – I plan and execute with minimal interruption. Faster but less control.\"}]\n\nSTEP 3: After receiving step 2 answer:\n  a) Run detect-environment.sh from the meta-setup skill scripts directory\n  b) Create .design-engineer.yaml with project type, selected mode, and detected environment\n  c) Scaffold docs/design/ folder via init-project-structure.sh from meta-setup scripts\n  d) Show brief environment results in plain language (use checkmarks, no technical names)\n  e) Make another AskUserQuestion: question=\"Would you like to install the status line?\" header=\"Status line\" options=[{label: \"Yes (Recommended)\", description: \"Shows model, usage limits, context bar, and pipeline progress below every prompt\"}, {label: \"No\", description: \"Skip – re-run /de:start later to install\"}]\n  f) If Yes, install status line per meta-setup skill Step 5 instructions\n\nSTEP 4: Say \"You're all set. Let's get started.\" then load the /de: command matching the goal:\n  Review what I have -> /de:review\n  Implement from Figma -> /de:dev\n  Design a new feature -> /de:design\n  Set up the dev workflow -> /de:dev\n\nIf user selected \"New product idea\" in step 1, skip steps 2-4 and load the meta-setup skill at Step 2 (Detect Environment) instead."}}
HOOK_EOF
fi
